version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "mambaforge-22.9"

conda:
  environment: .rtd_environment.yaml

sphinx:
  configuration: docs/source/conf.py

python:
  install:
    - method: pip
      path: .
