import numpy as np

from typing import Tuple

def integer16(signals: np.ndarray, filter: np.ndarray) -> np.ndarray: ...
def integer16Delayed(signals: np.ndarray, filter: np.ndarray, delay: int) -> np.ndarray: ...
def integerBeamformer(signals: np.ndarray, filters: np.ndarray, courses: np.ndarray, fines: np.ndarray, gains: np.ndarray) -> Tuple[np.ndarray,np.ndarray]: ...
