from typing import BinaryIO

from lsl.reader.cor import Frame as CORFrame
from lsl.reader.drspec import Frame as DRSpecFrame
from lsl.reader.drx import Frame as DRXFrame
from lsl.reader.drx8 import Frame as DRX8Frame
from lsl.reader.tbf import Frame as TBFFrame
from lsl.reader.tbn import Frame as TBNFrame
from lsl.reader.tbw import Frame as TBWFrame
from lsl.reader.vdif import Frame as VDIFFrame

def read_tbw(fh: BinaryIO, frame: TBWFrame) -> TBWFrame: ...
def read_tbn(fh: BinaryIO, frame: TBNFrame) -> TBNFrame: ...
def read_tbn_ci8(fh: BinaryIO, frame: TBNFrame) -> TBNFrame: ...
def read_drx(fh: BinaryIO, frame: DRXFrame) -> DRXFrame: ...
def read_drx_ci8(fh: BinaryIO, frame: DRXFrame) -> DRXFrame: ...
def read_drx8(fh: BinaryIO, frame: DRX8Frame) -> DRX8Frame: ...
def read_drx8_ci8(fh: BinaryIO, frame: DRX8Frame) -> DRX8Frame: ...
def read_drspec(fh: BinaryIO, frame: DRSpecFrame) -> DRSpecFrame: ...
def read_vdif(fh: BinaryIO, frame: VDIFFrame) -> VDIFFrame: ...
def read_vdif_i8(fh: BinaryIO, frame: VDIFFrame) -> VDIFFrame: ...
def read_tbf(fh: BinaryIO, frame: TBFFrame) -> TBFFrame: ...
def read_tbf_ci8(fh: BinaryIO, frame: TBFFrame) -> TBFFrame: ...
def read_cor(fh: BinaryIO, frame: CORFrame) -> CORFrame: ...

class SyncError(IOError): ...
class EOFError(IOError): ...

NCHAN_COR: int = ... 
