import numpy as np

from typing import Callable, Optional, Tuple

def FEngine(signals: np.ndarray, freqs: np.ndarray, delays: np.ndarray, LFFT: int=64, overlap: int=1, sample_rate: float=196e6, clip_level: int=0, window: Optional[Callable[[int],np.ndarray]]=None) -> Tuple[np.ndarray,np.ndarray]: ...

def PFBEngine(signals: np.ndarray, freqs: np.ndarray, delays: np.ndarray, LFFT: int=64, overlap: int=1, sample_rate: float=196e6, clip_level: int=0, window: Optional[Callable[[int],np.ndarray]]=None) -> Tuple[np.ndarray,np.ndarray]: ...

def XEngine2(signals1: np.ndarray, signals2: np.ndarray, valid1: np.ndarray, valid2: np.ndarray) -> np.ndarray: ...

def XEngine3(signalsX: np.ndarray, signalsY: np.ndarray, validX: np.ndarray, validY: np.ndarray) -> np.ndarray: ...
